"""
Typed data contracts for the Xrexze pipeline.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


class PanelState(enum.Enum):
    """Discrete states for the pipeline Kanban board."""
    PENDING = "Pending"
    SCRIPTING = "Scripting"
    AUDIO_SYNTHESIS = "Audio Synthesis"
    RENDERING = "Rendering"
    DONE = "Done"
    FAILED = "Failed"


@dataclass
class PanelMetadata:
    """
    Represents a single cropped panel extracted from a webtoon strip.

    Attributes:
        panel_id:       Sequential index (e.g. 1, 2, 3...).
        source_page:    Path to the original full-page image file.
        panel_path:     Path to the cropped panel image on disk.
        y_start:        Top pixel row in the source page (for debugging).
        y_end:          Bottom pixel row in the source page.
        width:          Panel width in pixels.
        height:         Panel height in pixels.
        state:          Current pipeline state.
    """
    panel_id: int
    source_page: Path
    panel_path: Path
    y_start: int
    y_end: int
    width: int
    height: int
    state: PanelState = PanelState.PENDING


@dataclass
class ScriptChunk:
    """
    Narration script generated by the VLM for a single panel.

    Attributes:
        panel_id:       References back to PanelMetadata.panel_id.
        narration_text: The Hindi/Hinglish narration string.
        raw_vlm_response: Full JSON response from the VLM for debugging.
        language:       Language variant used.
        estimated_duration_sec: Rough duration estimate from word count.
    """
    panel_id: int
    narration_text: str
    raw_vlm_response: str = ""
    language: str = "hindi_devanagari"
    estimated_duration_sec: float = 0.0


@dataclass
class AudioChunk:
    """
    Audio file generated by OmniVoice for a single panel's narration.

    Attributes:
        panel_id:       References PanelMetadata.panel_id.
        audio_path:     Path to the saved .wav file on disk.
        duration_sec:   Actual audio duration in seconds.
        sample_rate:    Sample rate of the wav (typically 24000 or 22050).
        file_size_bytes: Size on disk for memory budgeting.
    """
    panel_id: int
    audio_path: Path
    duration_sec: float
    sample_rate: int = 24000
    file_size_bytes: int = 0


@dataclass
class VideoChunk:
    """
    Rendered .mp4 chunk for a single panel (static image + audio).

    Attributes:
        panel_id:       References PanelMetadata.panel_id.
        video_path:     Path to the rendered .mp4 chunk on disk.
        duration_sec:   Duration matching the audio.
        resolution:     Tuple of (width, height).
        file_size_bytes: Size on disk.
    """
    panel_id: int
    video_path: Path
    duration_sec: float
    resolution: tuple[int, int] = (1920, 1080)
    file_size_bytes: int = 0


@dataclass
class ProjectManifest:
    """
    Persistent state for an entire project, enabling crash recovery.
    Serialized to JSON after every panel completes.

    Attributes:
        project_name:   User-defined project name.
        source_dir:     Directory containing raw webtoon pages.
        temp_dir:       Working directory for intermediate files.
        output_path:    Final output video path.
        panels:         Ordered list of all panel metadata.
        scripts:        Dict mapping panel_id -> ScriptChunk.
        audios:         Dict mapping panel_id -> AudioChunk.
        videos:         Dict mapping panel_id -> VideoChunk.
        last_completed_panel_id: For crash recovery; resume from here + 1.
    """
    project_name: str
    source_dir: Path
    temp_dir: Path
    output_path: Path
    panels: list[PanelMetadata] = field(default_factory=list)
    scripts: dict[int, ScriptChunk] = field(default_factory=dict)
    audios: dict[int, AudioChunk] = field(default_factory=dict)
    videos: dict[int, VideoChunk] = field(default_factory=dict)
    last_completed_panel_id: int = -1
